#!/bin/bash
echo "Download and Install script for SUPM 1.0"
case $1 in
install)
echo Downloading...
wget https://github.com/scratcher-402/supm-offical-repo/raw/main/${2}.sh
chmod 777 ${2}.sh
./${2}.sh
rm ${2}.sh
supm install ${2}.tar
;;
esac
